// <auto-generated />
using System;
using Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(ContextoJogo))]
    [Migration("20240312233722_InicioDB")]
    partial class InicioDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Domain.Models.AdivinhaInteiro", b =>
                {
                    b.Property<int>("COD_JOGADOR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HorarioJogo")
                        .HasColumnType("TEXT");

                    b.Property<int>("NUM_TENTATIVA")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("COD_JOGADOR");

                    b.ToTable("AdivinhaInteiro");
                });
#pragma warning restore 612, 618
        }
    }
}
